CREATE TABLE IF NOT EXISTS user(
    id INT  AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    email VARCHAR(255) NOT NULL,
    password VARCHAR(200) NOT NULL
);


CREATE TABLE IF NOT EXISTS projecto(
    id INT AUTO_INCREMENT PRIMARY KEY,
    nome VARCHAR(100) NOT NULL,
    descrition VARCHAR(300) NOT NULL,
    selecionar VARCHAR(50) NOT NULL,
    periodo TIMESTAMP DEFAULT CURRENT_TIMESTAMP
)